### PR TITLE
AIMD -> Reno (in most places)

### PR DESCRIPTION
**Pull request by larseggert**

### CODE REVIEW

**Review by goelvidhi — APPROVED** [review]

**Review by hinterop — CHANGES_REQUESTED** [review]
How about we remove "because they use..... " in "We refer to all Reno-style TCP standards and their variants collectively as "Reno TCP" below because they use the Additive Increase and Multiplicative Decrease algorithm (AIMD)."?

**Comment by lisongxu** [comment]
sorry that I forgot to switch from my another github account. hinterop is me.

**Review by bbriscoe — CHANGES_REQUESTED** [review]
Suggest delete " because they use the Additive Increase and Multiplicative Decrease algorithm (AIMD)" (with the change to Reno TCP in the first half of the sentene, the second half is no longer a rationale for the first half).

**Comment by bbriscoe** [comment]
My original comment and Neal's agreement with it asked for 
AIMD TCP -> Reno
not
AIMD TCP -> Reno TCP

Not only is AIMD too general, but TCP is too specific (it excludes Reno QUIC [RFC9002] for instance).

This terminology will need to be introduced differently. 
Current:
```
   This problem is equally
   applicable to all Reno-style TCP standards and their variants,
   including TCP-Reno [RFC5681], TCP-NewReno [RFC6582][RFC6675], SCTP
   [RFC4960], and TFRC [RFC5348], which use the same linear increase
   function for window growth.  We refer to all Reno-style TCP standards
   and their variants collectively as "AIMD TCP" below 
```
Suggested:
```
   This problem is equally
   applicable to all Reno-style standards and their variants,
   including TCP-Reno [RFC5681], TCP-NewReno [RFC6582][RFC6675], SCTP
   [RFC4960], TFRC [RFC5348] and QUIC congestion control [RFC9002], which use the same linear increase
   function for window growth.  We refer to all Reno-style standards
   and their variants collectively as "Reno" below 
```
(Personally, I wouldn't include New Reno, which is really different loss-recovery, not really different congestion control, but up to you...)

However, avoid a straight find+replace, because in some cases it really should say 'Reno TCP', for instance where [RFC5681] is cited, or where it is referring to experiments that were conducted specifically with Reno TCP, as in §5.1.

**Comment by larseggert** [comment]
@bbriscoe, I think I implemented your suggestions - review the PR again, please?

**Comment by bbriscoe** [comment]
I've got a number of proposed changes where find+replace isn't a good substitute for "engage brain". I think it's easiest if I fork from your latest changes and create another PR. Or would you really prefer a review of your PR?

**Comment by larseggert** [comment]
@bbriscoe I saw you proposed a PR to this branch, thanks! That's a great way to incorporate these changes,

**Review by hinterop — APPROVED** [review]

**Pull request merged**
