### PR TITLE
clarify alpha and add alpha_cubic

### LINKED ISSUE #64: Two meanings for a_aimd
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
> 5: Section 4.3  It seems to me that there are two meanings for a_aimd in this section. 
    One is the additive factor for CUBIC and the other is a generic parameter for AIMD() function. 
    This looks a bit confusing to me.

### PR DESCRIPTION
**Pull request by goelvidhi**
Closes #64 

As this PR includes changes to formulas in Section 4.3, reviewing the HTML version would be easier. You can download it from Editor's copy under Checks tab.

### CODE REVIEW

**Review by chromi — COMMENTED** [review]
This looks like it could be a significant improvement.  I look forward to seeing the formatted version.

**Comment by larseggert** [comment]
@chromi you can download the build artifacts here, which include the formatted versions: https://github.com/NTAP/rfc8312bis/suites/2996841176/artifacts/67729624

**Review by lisongxu — APPROVED** [review]
Thank you!

**Comment by lisongxu** [comment]
Thanks for this revision! It is very clear and I really like it.

**Comment by nsdyoshi** [comment]
looks very good to me.

**Pull request merged**
