### PR TITLE
add Vidhi as co-author

### LINKED ISSUE #17: Add Vidhi as co-author
@goelvidhi please prepare a pull request to add yourself to the authors' block and `CODEOWNERS`. Welcome aboard!

### PR DESCRIPTION
**Pull request by goelvidhi**
Closes #17.

As this is my first time to co-author an IETF document, please let me know if I missed something.

### CODE REVIEW

**Review by lisongxu — APPROVED** [review]
Thanks, Vidhi!

**Comment by larseggert** [comment]
Add yourself before me? Since I'm just doing editing, the folks who contribute content should come first. LGTM otherwise.

**Comment by goelvidhi** [comment]
> Add yourself before me? Since I'm just doing editing, the folks who contribute content should come first. LGTM otherwise.

ok, done.

**Comment by goelvidhi** [comment]
I am unable to understand why the markdown check failed. I only moved the text around. @larseggert, any ideas?

**Pull request merged**
