### PR TITLE
Use the contact hack for acknowledgments

### PR DESCRIPTION
**Pull request by martinthomson**
And compact them.

### CODE REVIEW

**Comment by larseggert** [comment]
What does "the contact hack" do?

**Review by goelvidhi — APPROVED** [review]
As long as Lars is ok with it :-)

**Comment by martinthomson** [comment]
The contact hack is using triple braces.  kramdown-rfc turns the included text into a `<contact>` element.  This is really what you want for names like this, but it also works if you have a need to use non-ASCII Unicode characters.

**Comment by larseggert** [comment]
@martinthomson I merged this without checking CI, and the build fails: https://github.com/NTAP/rfc8312bis/runs/8127710427?check_suite_focus=true#step:6:139

**Comment by martinthomson** [comment]
https://github.com/ietf-tools/xml2rfc/issues/519 ...

I'll send a fix for you.  The workaround is ugly, but whatever gets it working...

**Pull request merged**
