### PR TITLE
Address (some of) Lisong's review issues

### PR DESCRIPTION
**Pull request by larseggert**

### CODE REVIEW

**Review by lisongxu — APPROVED** [review]
Thanks, Lars

**Comment by larseggert** [comment]
@lisongxu do you have a suggestion for the one issue I didn't address yet?

>>Section 4.2: the cwnds used in Figure 2 and target equation are two different cwnds. In figure 2, cwnd is the cwnd at the beginning of the current congestion avoidance stage. In target (should also be referred to as Figure x?), cwnd is the current actual cwnd at time t.

> I need some help coming up with a solution to this one.

**Comment by lisongxu** [comment]
I will reply on github so that we can keep track of the discussions, Thanks
Lisong

________________________________

**Comment by lisongxu** [comment]
> @lisongxu do you have a suggestion for the one issue I didn't address yet?
> 
> > > Section 4.2: the cwnds used in Figure 2 and target equation are two different cwnds. In figure 2, cwnd is the cwnd at the beginning of the current congestion avoidance stage. In target (should also be referred to as Figure x?), cwnd is the current actual cwnd at time t.
> 
> > I need some help coming up with a solution to this one.

Because cwnd refers to the current cwnd in the whole RFC, except the cwnd in Figure 2. How about we define a new variable cwnd_{start} for just figure/equation 2 as we have discussed before?

That is, we change figure/equation 2 as follows, and replace all cwnd in the paragraph immediately below figure/equation 2 with cwnd_{start}.

K = \sqrt[3]{\frac{W_{max} - cwnd_{start}}{C}}

Update other sections accordingly as follow

In Section "Variables of interest", we add "cwnd_{start}: The cwnd at the beginning of the current congestion avoidance stage (i.e., at time epoch_{start})"

Thanks

**Comment by larseggert** [comment]
Thanks, I will make that change tomorrow and you guys can review after.

**Comment by larseggert** [comment]
OK, please review the changes. I am not sure if I managed to change `cwnd` to `cwnd_start` everywhere.

**Review by lisongxu — APPROVED** [review]
Thanks, Lars!

**Pull request merged**
